main.out : main.o fun1.o fun2.o sum.o
	gcc main.o fun1.o fun2.o sum.o -o main.out
main.o : main.c
	gcc -c main.c
fun1.o : fun1.c
	gcc -c fun1.c
fun2.o : fun2.c
	gcc -c fun2.c
sum.o : sum.c
	gcc -c sum.c
